export {
  SITE_NAME,
  SITE_DOMAIN,
  SITE_URL,
  SITE_SUPPORT_EMAIL,
  SITE_SUPPORT_WHATSAPP,
  SITE_SUPPORT_PHONE_DISPLAY,
  FORM_PHONE_PLACEHOLDER,
  DOCTOR_LOGIN_EMAIL_PLACEHOLDER,
  ADMIN_LOGIN_EMAIL_PLACEHOLDER,
  whatsappHref,
  mailtoHref,
} from "@pal-dental/shared";
