/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/.next/types/validator`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/app/offers/page`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/app/blog/page`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/components/SiteFooter`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/doctor/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/.next/types/validator`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/app/offers/page`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/app/blog/page`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/components/SiteFooter`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/doctor/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../../web/.next/types/validator${`?${string}` | `#${string}` | ''}` | `/../../web/app/offers/page${`?${string}` | `#${string}` | ''}` | `/../../web/app/blog/page${`?${string}` | `#${string}` | ''}` | `/../../web/components/SiteFooter${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/.next/types/validator`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/app/offers/page`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/app/blog/page`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/components/SiteFooter`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/doctor/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/doctor/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
