/** Malamih brand theme — aligned to deep teal / cream identity board */
export const theme = {
  navy: "#0a1628",
  navySoft: "#0f172a",
  navyGlass: "rgba(10, 22, 40, 0.88)",
  teal: "#0c5e47",
  tealLight: "#1a7a64",
  tealMuted: "#e8f2ee",
  gold: "#d4af37",
  goldLight: "#e8c86a",
  goldMuted: "#f7f1e0",
  /** Legacy aliases → brand teal/gold (no purple/sky chrome) */
  sky: "#1a7a64",
  skyMuted: "#e8f2ee",
  purple: "#0c5e47",
  purpleMuted: "#e8f2ee",
  pink: "#0a4d3a",
  pinkMuted: "#eef6f3",
  bg: "#f7f5f0",
  bgElevated: "#f0ebe3",
  card: "#ffffff",
  cardGlass: "rgba(255,255,255,0.92)",
  border: "#e5e0d8",
  borderLight: "#efece6",
  text: "#0a1628",
  textMuted: "#5c6570",
  textSoft: "#8a929c",
  white: "#ffffff",
  offerGradient: ["#0a1628", "#0c5e47"] as const,
  promoGradient: ["#0a1628", "#0c5e47"] as const,
  radius: {
    sm: 14,
    md: 18,
    lg: 22,
    xl: 26,
    xxl: 32,
    pill: 999,
  },
  shadow: {
    card: {
      shadowColor: "#0a1628",
      shadowOpacity: 0.07,
      shadowOffset: { width: 0, height: 8 },
      shadowRadius: 24,
      elevation: 4,
    },
    float: {
      shadowColor: "#0a1628",
      shadowOpacity: 0.12,
      shadowOffset: { width: 0, height: 12 },
      shadowRadius: 32,
      elevation: 8,
    },
    glow: {
      shadowColor: "#0c5e47",
      shadowOpacity: 0.22,
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 16,
      elevation: 3,
    },
  },
} as const;

/** @deprecated use `theme` */
export const colors = {
  ink: theme.navy,
  amber: theme.gold,
  primary: theme.teal,
  background: theme.bg,
  white: theme.white,
  border: theme.border,
} as const;
